// Code generated by mockery v2.42.1. DO NOT EDIT.

package io

import mock "github.com/stretchr/testify/mock"

// MockByteReader is an autogenerated mock type for the ByteReader type
type MockByteReader struct {
	mock.Mock
}

type MockByteReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockByteReader) EXPECT() *MockByteReader_Expecter {
	return &MockByteReader_Expecter{mock: &_m.Mock}
}

// ReadByte provides a mock function with given fields:
func (_m *MockByteReader) ReadByte() (byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadByte")
	}

	var r0 byte
	var r1 error
	if rf, ok := ret.Get(0).(func() (byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() byte); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(byte)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockByteReader_ReadByte_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadByte'
type MockByteReader_ReadByte_Call struct {
	*mock.Call
}

// ReadByte is a helper method to define mock.On call
func (_e *MockByteReader_Expecter) ReadByte() *MockByteReader_ReadByte_Call {
	return &MockByteReader_ReadByte_Call{Call: _e.mock.On("ReadByte")}
}

func (_c *MockByteReader_ReadByte_Call) Run(run func()) *MockByteReader_ReadByte_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockByteReader_ReadByte_Call) Return(_a0 byte, _a1 error) *MockByteReader_ReadByte_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockByteReader_ReadByte_Call) RunAndReturn(run func() (byte, error)) *MockByteReader_ReadByte_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockByteReader creates a new instance of MockByteReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockByteReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockByteReader {
	mock := &MockByteReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
