// Code generated by mockery v2.42.1. DO NOT EDIT.

package io

import mock "github.com/stretchr/testify/mock"

// MockWriterAt is an autogenerated mock type for the WriterAt type
type MockWriterAt struct {
	mock.Mock
}

type MockWriterAt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriterAt) EXPECT() *MockWriterAt_Expecter {
	return &MockWriterAt_Expecter{mock: &_m.Mock}
}

// WriteAt provides a mock function with given fields: p, off
func (_m *MockWriterAt) WriteAt(p []byte, off int64) (int, error) {
	ret := _m.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for WriteAt")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return rf(p, off)
	}
	if rf, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = rf(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = rf(p, off)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWriterAt_WriteAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAt'
type MockWriterAt_WriteAt_Call struct {
	*mock.Call
}

// WriteAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *MockWriterAt_Expecter) WriteAt(p interface{}, off interface{}) *MockWriterAt_WriteAt_Call {
	return &MockWriterAt_WriteAt_Call{Call: _e.mock.On("WriteAt", p, off)}
}

func (_c *MockWriterAt_WriteAt_Call) Run(run func(p []byte, off int64)) *MockWriterAt_WriteAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(int64))
	})
	return _c
}

func (_c *MockWriterAt_WriteAt_Call) Return(n int, err error) *MockWriterAt_WriteAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWriterAt_WriteAt_Call) RunAndReturn(run func([]byte, int64) (int, error)) *MockWriterAt_WriteAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriterAt creates a new instance of MockWriterAt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriterAt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriterAt {
	mock := &MockWriterAt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
