// Code generated by mockery v2.42.1. DO NOT EDIT.

package io

import mock "github.com/stretchr/testify/mock"

// MockRuneReader is an autogenerated mock type for the RuneReader type
type MockRuneReader struct {
	mock.Mock
}

type MockRuneReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuneReader) EXPECT() *MockRuneReader_Expecter {
	return &MockRuneReader_Expecter{mock: &_m.Mock}
}

// ReadRune provides a mock function with given fields:
func (_m *MockRuneReader) ReadRune() (rune, int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadRune")
	}

	var r0 rune
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func() (rune, int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() rune); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(rune)
	}

	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRuneReader_ReadRune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRune'
type MockRuneReader_ReadRune_Call struct {
	*mock.Call
}

// ReadRune is a helper method to define mock.On call
func (_e *MockRuneReader_Expecter) ReadRune() *MockRuneReader_ReadRune_Call {
	return &MockRuneReader_ReadRune_Call{Call: _e.mock.On("ReadRune")}
}

func (_c *MockRuneReader_ReadRune_Call) Run(run func()) *MockRuneReader_ReadRune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRuneReader_ReadRune_Call) Return(r rune, size int, err error) *MockRuneReader_ReadRune_Call {
	_c.Call.Return(r, size, err)
	return _c
}

func (_c *MockRuneReader_ReadRune_Call) RunAndReturn(run func() (rune, int, error)) *MockRuneReader_ReadRune_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuneReader creates a new instance of MockRuneReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuneReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuneReader {
	mock := &MockRuneReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
