// Code generated by mockery v2.42.1. DO NOT EDIT.

package io

import mock "github.com/stretchr/testify/mock"

// MockByteScanner is an autogenerated mock type for the ByteScanner type
type MockByteScanner struct {
	mock.Mock
}

type MockByteScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockByteScanner) EXPECT() *MockByteScanner_Expecter {
	return &MockByteScanner_Expecter{mock: &_m.Mock}
}

// ReadByte provides a mock function with given fields:
func (_m *MockByteScanner) ReadByte() (byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadByte")
	}

	var r0 byte
	var r1 error
	if rf, ok := ret.Get(0).(func() (byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() byte); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(byte)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockByteScanner_ReadByte_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadByte'
type MockByteScanner_ReadByte_Call struct {
	*mock.Call
}

// ReadByte is a helper method to define mock.On call
func (_e *MockByteScanner_Expecter) ReadByte() *MockByteScanner_ReadByte_Call {
	return &MockByteScanner_ReadByte_Call{Call: _e.mock.On("ReadByte")}
}

func (_c *MockByteScanner_ReadByte_Call) Run(run func()) *MockByteScanner_ReadByte_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockByteScanner_ReadByte_Call) Return(_a0 byte, _a1 error) *MockByteScanner_ReadByte_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockByteScanner_ReadByte_Call) RunAndReturn(run func() (byte, error)) *MockByteScanner_ReadByte_Call {
	_c.Call.Return(run)
	return _c
}

// UnreadByte provides a mock function with given fields:
func (_m *MockByteScanner) UnreadByte() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnreadByte")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockByteScanner_UnreadByte_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnreadByte'
type MockByteScanner_UnreadByte_Call struct {
	*mock.Call
}

// UnreadByte is a helper method to define mock.On call
func (_e *MockByteScanner_Expecter) UnreadByte() *MockByteScanner_UnreadByte_Call {
	return &MockByteScanner_UnreadByte_Call{Call: _e.mock.On("UnreadByte")}
}

func (_c *MockByteScanner_UnreadByte_Call) Run(run func()) *MockByteScanner_UnreadByte_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockByteScanner_UnreadByte_Call) Return(_a0 error) *MockByteScanner_UnreadByte_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockByteScanner_UnreadByte_Call) RunAndReturn(run func() error) *MockByteScanner_UnreadByte_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockByteScanner creates a new instance of MockByteScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockByteScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockByteScanner {
	mock := &MockByteScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
