// Code generated by mockery v2.42.1. DO NOT EDIT.

package io

import mock "github.com/stretchr/testify/mock"

// MockReadWriteSeeker is an autogenerated mock type for the ReadWriteSeeker type
type MockReadWriteSeeker struct {
	mock.Mock
}

type MockReadWriteSeeker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadWriteSeeker) EXPECT() *MockReadWriteSeeker_Expecter {
	return &MockReadWriteSeeker_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: p
func (_m *MockReadWriteSeeker) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadWriteSeeker_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockReadWriteSeeker_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *MockReadWriteSeeker_Expecter) Read(p interface{}) *MockReadWriteSeeker_Read_Call {
	return &MockReadWriteSeeker_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *MockReadWriteSeeker_Read_Call) Run(run func(p []byte)) *MockReadWriteSeeker_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockReadWriteSeeker_Read_Call) Return(n int, err error) *MockReadWriteSeeker_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReadWriteSeeker_Read_Call) RunAndReturn(run func([]byte) (int, error)) *MockReadWriteSeeker_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function with given fields: offset, whence
func (_m *MockReadWriteSeeker) Seek(offset int64, whence int) (int64, error) {
	ret := _m.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return rf(offset, whence)
	}
	if rf, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = rf(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(offset, whence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadWriteSeeker_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockReadWriteSeeker_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *MockReadWriteSeeker_Expecter) Seek(offset interface{}, whence interface{}) *MockReadWriteSeeker_Seek_Call {
	return &MockReadWriteSeeker_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *MockReadWriteSeeker_Seek_Call) Run(run func(offset int64, whence int)) *MockReadWriteSeeker_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *MockReadWriteSeeker_Seek_Call) Return(_a0 int64, _a1 error) *MockReadWriteSeeker_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadWriteSeeker_Seek_Call) RunAndReturn(run func(int64, int) (int64, error)) *MockReadWriteSeeker_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *MockReadWriteSeeker) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadWriteSeeker_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockReadWriteSeeker_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockReadWriteSeeker_Expecter) Write(p interface{}) *MockReadWriteSeeker_Write_Call {
	return &MockReadWriteSeeker_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockReadWriteSeeker_Write_Call) Run(run func(p []byte)) *MockReadWriteSeeker_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockReadWriteSeeker_Write_Call) Return(n int, err error) *MockReadWriteSeeker_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReadWriteSeeker_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockReadWriteSeeker_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadWriteSeeker creates a new instance of MockReadWriteSeeker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadWriteSeeker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadWriteSeeker {
	mock := &MockReadWriteSeeker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
