// Code generated by mockery v2.43.2. DO NOT EDIT.

package otel

import mock "github.com/stretchr/testify/mock"

// MockErrorHandlerFunc is an autogenerated mock type for the ErrorHandlerFunc type
type MockErrorHandlerFunc struct {
	mock.Mock
}

type MockErrorHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorHandlerFunc) EXPECT() *MockErrorHandlerFunc_Expecter {
	return &MockErrorHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockErrorHandlerFunc) Execute(_a0 error) {
	_m.Called(_a0)
}

// MockErrorHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockErrorHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 error
func (_e *MockErrorHandlerFunc_Expecter) Execute(_a0 interface{}) *MockErrorHandlerFunc_Execute_Call {
	return &MockErrorHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockErrorHandlerFunc_Execute_Call) Run(run func(_a0 error)) *MockErrorHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockErrorHandlerFunc_Execute_Call) Return() *MockErrorHandlerFunc_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandlerFunc_Execute_Call) RunAndReturn(run func(error)) *MockErrorHandlerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockErrorHandlerFunc creates a new instance of MockErrorHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorHandlerFunc {
	mock := &MockErrorHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
