// Code generated by mockery v2.43.2. DO NOT EDIT.

package adapters

import (
	config "mox/pkg/config"

	mock "github.com/stretchr/testify/mock"
)

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockAdapter) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdapter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAdapter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockAdapter_Expecter) Close() *MockAdapter_Close_Call {
	return &MockAdapter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockAdapter_Close_Call) Run(run func()) *MockAdapter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdapter_Close_Call) Return(_a0 error) *MockAdapter_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdapter_Close_Call) RunAndReturn(run func() error) *MockAdapter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function with given fields: _a0
func (_m *MockAdapter) Connect(_a0 config.Database) (interface{}, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(config.Database) (interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(config.Database) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(config.Database) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockAdapter_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - _a0 config.Database
func (_e *MockAdapter_Expecter) Connect(_a0 interface{}) *MockAdapter_Connect_Call {
	return &MockAdapter_Connect_Call{Call: _e.mock.On("Connect", _a0)}
}

func (_c *MockAdapter_Connect_Call) Run(run func(_a0 config.Database)) *MockAdapter_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Database))
	})
	return _c
}

func (_c *MockAdapter_Connect_Call) Return(_a0 interface{}, _a1 error) *MockAdapter_Connect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_Connect_Call) RunAndReturn(run func(config.Database) (interface{}, error)) *MockAdapter_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// DriverName provides a mock function with given fields:
func (_m *MockAdapter) DriverName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DriverName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAdapter_DriverName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DriverName'
type MockAdapter_DriverName_Call struct {
	*mock.Call
}

// DriverName is a helper method to define mock.On call
func (_e *MockAdapter_Expecter) DriverName() *MockAdapter_DriverName_Call {
	return &MockAdapter_DriverName_Call{Call: _e.mock.On("DriverName")}
}

func (_c *MockAdapter_DriverName_Call) Run(run func()) *MockAdapter_DriverName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdapter_DriverName_Call) Return(_a0 string) *MockAdapter_DriverName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdapter_DriverName_Call) RunAndReturn(run func() string) *MockAdapter_DriverName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
