// Code generated by mockery v2.43.2. DO NOT EDIT.

package driver

import mock "github.com/stretchr/testify/mock"

// MockIDriver is an autogenerated mock type for the IDriver type
type MockIDriver struct {
	mock.Mock
}

type MockIDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDriver) EXPECT() *MockIDriver_Expecter {
	return &MockIDriver_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockIDriver) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDriver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDriver_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDriver_Expecter) Close() *MockIDriver_Close_Call {
	return &MockIDriver_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDriver_Close_Call) Run(run func()) *MockIDriver_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDriver_Close_Call) Return(_a0 error) *MockIDriver_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDriver_Close_Call) RunAndReturn(run func() error) *MockIDriver_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields:
func (_m *MockIDriver) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDriver_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockIDriver_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockIDriver_Expecter) Init() *MockIDriver_Init_Call {
	return &MockIDriver_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *MockIDriver_Init_Call) Run(run func()) *MockIDriver_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDriver_Init_Call) Return(_a0 error) *MockIDriver_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDriver_Init_Call) RunAndReturn(run func() error) *MockIDriver_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Instance provides a mock function with given fields:
func (_m *MockIDriver) Instance() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Instance")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockIDriver_Instance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instance'
type MockIDriver_Instance_Call struct {
	*mock.Call
}

// Instance is a helper method to define mock.On call
func (_e *MockIDriver_Expecter) Instance() *MockIDriver_Instance_Call {
	return &MockIDriver_Instance_Call{Call: _e.mock.On("Instance")}
}

func (_c *MockIDriver_Instance_Call) Run(run func()) *MockIDriver_Instance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDriver_Instance_Call) Return(_a0 interface{}) *MockIDriver_Instance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDriver_Instance_Call) RunAndReturn(run func() interface{}) *MockIDriver_Instance_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *MockIDriver) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDriver_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockIDriver_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockIDriver_Expecter) Name() *MockIDriver_Name_Call {
	return &MockIDriver_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockIDriver_Name_Call) Run(run func()) *MockIDriver_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDriver_Name_Call) Return(_a0 string) *MockIDriver_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDriver_Name_Call) RunAndReturn(run func() string) *MockIDriver_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDriver creates a new instance of MockIDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDriver {
	mock := &MockIDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
