// Code generated by mockery v2.43.2. DO NOT EDIT.

package datamanager

import mock "github.com/stretchr/testify/mock"

// MockDataAdapter is an autogenerated mock type for the DataAdapter type
type MockDataAdapter struct {
	mock.Mock
}

type MockDataAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataAdapter) EXPECT() *MockDataAdapter_Expecter {
	return &MockDataAdapter_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: f
func (_m *MockDataAdapter) Connect(f func(error)) {
	_m.Called(f)
}

// MockDataAdapter_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDataAdapter_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - f func(error)
func (_e *MockDataAdapter_Expecter) Connect(f interface{}) *MockDataAdapter_Connect_Call {
	return &MockDataAdapter_Connect_Call{Call: _e.mock.On("Connect", f)}
}

func (_c *MockDataAdapter_Connect_Call) Run(run func(f func(error))) *MockDataAdapter_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(error)))
	})
	return _c
}

func (_c *MockDataAdapter_Connect_Call) Return() *MockDataAdapter_Connect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDataAdapter_Connect_Call) RunAndReturn(run func(func(error))) *MockDataAdapter_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields: f
func (_m *MockDataAdapter) Disconnect(f func(error)) {
	_m.Called(f)
}

// MockDataAdapter_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockDataAdapter_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - f func(error)
func (_e *MockDataAdapter_Expecter) Disconnect(f interface{}) *MockDataAdapter_Disconnect_Call {
	return &MockDataAdapter_Disconnect_Call{Call: _e.mock.On("Disconnect", f)}
}

func (_c *MockDataAdapter_Disconnect_Call) Run(run func(f func(error))) *MockDataAdapter_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(error)))
	})
	return _c
}

func (_c *MockDataAdapter_Disconnect_Call) Return() *MockDataAdapter_Disconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDataAdapter_Disconnect_Call) RunAndReturn(run func(func(error))) *MockDataAdapter_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: connectionName
func (_m *MockDataAdapter) Get(connectionName string) interface{} {
	ret := _m.Called(connectionName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(connectionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockDataAdapter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDataAdapter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - connectionName string
func (_e *MockDataAdapter_Expecter) Get(connectionName interface{}) *MockDataAdapter_Get_Call {
	return &MockDataAdapter_Get_Call{Call: _e.mock.On("Get", connectionName)}
}

func (_c *MockDataAdapter_Get_Call) Run(run func(connectionName string)) *MockDataAdapter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDataAdapter_Get_Call) Return(_a0 interface{}) *MockDataAdapter_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDataAdapter_Get_Call) RunAndReturn(run func(string) interface{}) *MockDataAdapter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDataAdapter creates a new instance of MockDataAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataAdapter {
	mock := &MockDataAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
