// Code generated by mockery v2.43.2. DO NOT EDIT.

package service

import (
	context "context"

	dto "mox/use_cases/orders/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, payload
func (_m *MockOrderService) CreateOrder(ctx context.Context, payload dto.CreateOrderRequest) (dto.CreateOrderResponse, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 dto.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateOrderRequest) (dto.CreateOrderResponse, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateOrderRequest) dto.CreateOrderResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.CreateOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateOrderRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.CreateOrderRequest
func (_e *MockOrderService_Expecter) CreateOrder(ctx interface{}, payload interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, payload)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, payload dto.CreateOrderRequest)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateOrderRequest))
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(_a0 dto.CreateOrderResponse, _a1 error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, dto.CreateOrderRequest) (dto.CreateOrderResponse, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
