// Code generated by mockery v2.43.2. DO NOT EDIT.

package repository

import (
	context "context"
	dto "mox/use_cases/orders/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// SaveOrder provides a mock function with given fields: ctx, payload
func (_m *MockOrderRepository) SaveOrder(ctx context.Context, payload dto.CreateOrderRequest) (dto.CreateOrderRepositoryResult, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 dto.CreateOrderRepositoryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateOrderRequest) (dto.CreateOrderRepositoryResult, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateOrderRequest) dto.CreateOrderRepositoryResult); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.CreateOrderRepositoryResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateOrderRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type MockOrderRepository_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.CreateOrderRequest
func (_e *MockOrderRepository_Expecter) SaveOrder(ctx interface{}, payload interface{}) *MockOrderRepository_SaveOrder_Call {
	return &MockOrderRepository_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, payload)}
}

func (_c *MockOrderRepository_SaveOrder_Call) Run(run func(ctx context.Context, payload dto.CreateOrderRequest)) *MockOrderRepository_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateOrderRequest))
	})
	return _c
}

func (_c *MockOrderRepository_SaveOrder_Call) Return(_a0 dto.CreateOrderRepositoryResult, _a1 error) *MockOrderRepository_SaveOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_SaveOrder_Call) RunAndReturn(run func(context.Context, dto.CreateOrderRequest) (dto.CreateOrderRepositoryResult, error)) *MockOrderRepository_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
