// Code generated by mockery v2.43.2. DO NOT EDIT.

package listener

import (
	dto "goodin/use_cases/orders/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderReportListener is an autogenerated mock type for the OrderReportListener type
type MockOrderReportListener struct {
	mock.Mock
}

type MockOrderReportListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderReportListener) EXPECT() *MockOrderReportListener_Expecter {
	return &MockOrderReportListener_Expecter{mock: &_m.Mock}
}

// Receive provides a mock function with given fields: payload
func (_m *MockOrderReportListener) Receive(payload *dto.Order) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.Order) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderReportListener_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockOrderReportListener_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - payload *dto.Order
func (_e *MockOrderReportListener_Expecter) Receive(payload interface{}) *MockOrderReportListener_Receive_Call {
	return &MockOrderReportListener_Receive_Call{Call: _e.mock.On("Receive", payload)}
}

func (_c *MockOrderReportListener_Receive_Call) Run(run func(payload *dto.Order)) *MockOrderReportListener_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.Order))
	})
	return _c
}

func (_c *MockOrderReportListener_Receive_Call) Return(_a0 error) *MockOrderReportListener_Receive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderReportListener_Receive_Call) RunAndReturn(run func(*dto.Order) error) *MockOrderReportListener_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderReportListener creates a new instance of MockOrderReportListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderReportListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderReportListener {
	mock := &MockOrderReportListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
