// Code generated by mockery v2.43.2. DO NOT EDIT.

package messaging

import (
	dto "mox/use_cases/orders/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderPublisher is an autogenerated mock type for the OrderPublisher type
type MockOrderPublisher struct {
	mock.Mock
}

type MockOrderPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPublisher) EXPECT() *MockOrderPublisher_Expecter {
	return &MockOrderPublisher_Expecter{mock: &_m.Mock}
}

// PublishOrder provides a mock function with given fields: payload
func (_m *MockOrderPublisher) PublishOrder(payload *dto.Order) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.Order) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderPublisher_PublishOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrder'
type MockOrderPublisher_PublishOrder_Call struct {
	*mock.Call
}

// PublishOrder is a helper method to define mock.On call
//   - payload *dto.Order
func (_e *MockOrderPublisher_Expecter) PublishOrder(payload interface{}) *MockOrderPublisher_PublishOrder_Call {
	return &MockOrderPublisher_PublishOrder_Call{Call: _e.mock.On("PublishOrder", payload)}
}

func (_c *MockOrderPublisher_PublishOrder_Call) Run(run func(payload *dto.Order)) *MockOrderPublisher_PublishOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.Order))
	})
	return _c
}

func (_c *MockOrderPublisher_PublishOrder_Call) Return(_a0 error) *MockOrderPublisher_PublishOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderPublisher_PublishOrder_Call) RunAndReturn(run func(*dto.Order) error) *MockOrderPublisher_PublishOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderPublisher creates a new instance of MockOrderPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPublisher {
	mock := &MockOrderPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
