// Code generated by mockery v2.43.2. DO NOT EDIT.

package request

import (
	dto "goodin/use_cases/orders/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockCustomerDetailRequest is an autogenerated mock type for the CustomerDetailRequest type
type MockCustomerDetailRequest struct {
	mock.Mock
}

type MockCustomerDetailRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerDetailRequest) EXPECT() *MockCustomerDetailRequest_Expecter {
	return &MockCustomerDetailRequest_Expecter{mock: &_m.Mock}
}

// GetDetailCustomer provides a mock function with given fields: payload
func (_m *MockCustomerDetailRequest) GetDetailCustomer(payload *dto.CustomerDetailRequest) dto.CustomerDetailResponse {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailCustomer")
	}

	var r0 dto.CustomerDetailResponse
	if rf, ok := ret.Get(0).(func(*dto.CustomerDetailRequest) dto.CustomerDetailResponse); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(dto.CustomerDetailResponse)
	}

	return r0
}

// MockCustomerDetailRequest_GetDetailCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailCustomer'
type MockCustomerDetailRequest_GetDetailCustomer_Call struct {
	*mock.Call
}

// GetDetailCustomer is a helper method to define mock.On call
//   - payload *dto.CustomerDetailRequest
func (_e *MockCustomerDetailRequest_Expecter) GetDetailCustomer(payload interface{}) *MockCustomerDetailRequest_GetDetailCustomer_Call {
	return &MockCustomerDetailRequest_GetDetailCustomer_Call{Call: _e.mock.On("GetDetailCustomer", payload)}
}

func (_c *MockCustomerDetailRequest_GetDetailCustomer_Call) Run(run func(payload *dto.CustomerDetailRequest)) *MockCustomerDetailRequest_GetDetailCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.CustomerDetailRequest))
	})
	return _c
}

func (_c *MockCustomerDetailRequest_GetDetailCustomer_Call) Return(_a0 dto.CustomerDetailResponse) *MockCustomerDetailRequest_GetDetailCustomer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerDetailRequest_GetDetailCustomer_Call) RunAndReturn(run func(*dto.CustomerDetailRequest) dto.CustomerDetailResponse) *MockCustomerDetailRequest_GetDetailCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerDetailRequest creates a new instance of MockCustomerDetailRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerDetailRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerDetailRequest {
	mock := &MockCustomerDetailRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
